/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JourneySession = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Int,
  'status' : IDL.Text,
  'destination' : IDL.Text,
  'userId' : IDL.Text,
  'isActive' : IDL.Bool,
  'currentLong' : IDL.Float64,
  'currentLat' : IDL.Float64,
  'estimatedArrival' : IDL.Int,
});
export const AlertLog = IDL.Record({
  'id' : IDL.Text,
  'lat' : IDL.Float64,
  'alertType' : IDL.Text,
  'contactsNotified' : IDL.Nat,
  'mapLink' : IDL.Text,
  'isMockMode' : IDL.Bool,
  'userId' : IDL.Text,
  'long' : IDL.Float64,
  'errorDetails' : IDL.Opt(IDL.Text),
  'failedContacts' : IDL.Vec(IDL.Text),
  'timestamp' : IDL.Int,
  'providerUsed' : IDL.Text,
  'overallStatus' : IDL.Text,
  'locationAccuracy' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'bloodGroup' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const EmergencyContact = IDL.Record({
  'id' : IDL.Text,
  'relationship' : IDL.Text,
  'isGuardian' : IDL.Bool,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const SafeZone = IDL.Record({
  'id' : IDL.Text,
  'lat' : IDL.Float64,
  'long' : IDL.Float64,
  'name' : IDL.Text,
  'zoneLabel' : IDL.Text,
  'radius' : IDL.Float64,
});
export const SystemStats = IDL.Record({
  'totalAutoAlerts' : IDL.Nat,
  'failedDeliveries' : IDL.Nat,
  'totalSosAlerts' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalDeliveries' : IDL.Nat,
});
export const AlertResult = IDL.Record({
  'status' : IDL.Text,
  'contactsNotified' : IDL.Nat,
  'mapLink' : IDL.Text,
  'isMockMode' : IDL.Bool,
  'failedContacts' : IDL.Vec(IDL.Text),
  'providerUsed' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAlertLogs' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteEmergencyContact' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteSafeZone' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'endJourney' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getActiveJourney' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(JourneySession)],
      ['query'],
    ),
  'getAlertLogs' : IDL.Func([IDL.Text], [IDL.Vec(AlertLog)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmergencyContacts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EmergencyContact)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getSafeZones' : IDL.Func([IDL.Text], [IDL.Vec(SafeZone)], ['query']),
  'getSystemStats' : IDL.Func([], [SystemStats], ['query']),
  'getTwilioStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'isMockMode' : IDL.Bool,
          'configured' : IDL.Bool,
          'fromNumber' : IDL.Opt(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveEmergencyContact' : IDL.Func(
      [IDL.Text, EmergencyContact],
      [IDL.Text],
      [],
    ),
  'saveProfile' : IDL.Func([IDL.Text, UserProfile], [IDL.Bool], []),
  'saveSafeZone' : IDL.Func([IDL.Text, SafeZone], [IDL.Text], []),
  'sendAutoLocationAlert' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Int],
      [AlertResult],
      [],
    ),
  'sendSosAlert' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Text, IDL.Int],
      [AlertResult],
      [],
    ),
  'setTwilioConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'startJourney' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateJourneyLocation' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JourneySession = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Int,
    'status' : IDL.Text,
    'destination' : IDL.Text,
    'userId' : IDL.Text,
    'isActive' : IDL.Bool,
    'currentLong' : IDL.Float64,
    'currentLat' : IDL.Float64,
    'estimatedArrival' : IDL.Int,
  });
  const AlertLog = IDL.Record({
    'id' : IDL.Text,
    'lat' : IDL.Float64,
    'alertType' : IDL.Text,
    'contactsNotified' : IDL.Nat,
    'mapLink' : IDL.Text,
    'isMockMode' : IDL.Bool,
    'userId' : IDL.Text,
    'long' : IDL.Float64,
    'errorDetails' : IDL.Opt(IDL.Text),
    'failedContacts' : IDL.Vec(IDL.Text),
    'timestamp' : IDL.Int,
    'providerUsed' : IDL.Text,
    'overallStatus' : IDL.Text,
    'locationAccuracy' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'bloodGroup' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const EmergencyContact = IDL.Record({
    'id' : IDL.Text,
    'relationship' : IDL.Text,
    'isGuardian' : IDL.Bool,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SafeZone = IDL.Record({
    'id' : IDL.Text,
    'lat' : IDL.Float64,
    'long' : IDL.Float64,
    'name' : IDL.Text,
    'zoneLabel' : IDL.Text,
    'radius' : IDL.Float64,
  });
  const SystemStats = IDL.Record({
    'totalAutoAlerts' : IDL.Nat,
    'failedDeliveries' : IDL.Nat,
    'totalSosAlerts' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalDeliveries' : IDL.Nat,
  });
  const AlertResult = IDL.Record({
    'status' : IDL.Text,
    'contactsNotified' : IDL.Nat,
    'mapLink' : IDL.Text,
    'isMockMode' : IDL.Bool,
    'failedContacts' : IDL.Vec(IDL.Text),
    'providerUsed' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAlertLogs' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteEmergencyContact' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteSafeZone' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'endJourney' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getActiveJourney' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(JourneySession)],
        ['query'],
      ),
    'getAlertLogs' : IDL.Func([IDL.Text], [IDL.Vec(AlertLog)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmergencyContacts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EmergencyContact)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getSafeZones' : IDL.Func([IDL.Text], [IDL.Vec(SafeZone)], ['query']),
    'getSystemStats' : IDL.Func([], [SystemStats], ['query']),
    'getTwilioStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'isMockMode' : IDL.Bool,
            'configured' : IDL.Bool,
            'fromNumber' : IDL.Opt(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveEmergencyContact' : IDL.Func(
        [IDL.Text, EmergencyContact],
        [IDL.Text],
        [],
      ),
    'saveProfile' : IDL.Func([IDL.Text, UserProfile], [IDL.Bool], []),
    'saveSafeZone' : IDL.Func([IDL.Text, SafeZone], [IDL.Text], []),
    'sendAutoLocationAlert' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Int],
        [AlertResult],
        [],
      ),
    'sendSosAlert' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Text, IDL.Int],
        [AlertResult],
        [],
      ),
    'setTwilioConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'startJourney' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateJourneyLocation' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };