/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlertLog {
  'id' : string,
  'lat' : number,
  'alertType' : string,
  'contactsNotified' : bigint,
  'mapLink' : string,
  'isMockMode' : boolean,
  'userId' : string,
  'long' : number,
  'errorDetails' : [] | [string],
  'failedContacts' : Array<string>,
  'timestamp' : bigint,
  'providerUsed' : string,
  'overallStatus' : string,
  'locationAccuracy' : number,
}
export interface AlertResult {
  'status' : string,
  'contactsNotified' : bigint,
  'mapLink' : string,
  'isMockMode' : boolean,
  'failedContacts' : Array<string>,
  'providerUsed' : string,
}
export interface EmergencyContact {
  'id' : string,
  'relationship' : string,
  'isGuardian' : boolean,
  'name' : string,
  'phone' : string,
}
export interface JourneySession {
  'id' : string,
  'startTime' : bigint,
  'status' : string,
  'destination' : string,
  'userId' : string,
  'isActive' : boolean,
  'currentLong' : number,
  'currentLat' : number,
  'estimatedArrival' : bigint,
}
export interface SafeZone {
  'id' : string,
  'lat' : number,
  'long' : number,
  'name' : string,
  'zoneLabel' : string,
  'radius' : number,
}
export interface SystemStats {
  'totalAutoAlerts' : bigint,
  'failedDeliveries' : bigint,
  'totalSosAlerts' : bigint,
  'totalUsers' : bigint,
  'totalDeliveries' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'bloodGroup' : [] | [string],
  'address' : [] | [string],
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAlertLogs' : ActorMethod<[string], boolean>,
  'deleteEmergencyContact' : ActorMethod<[string, string], boolean>,
  'deleteSafeZone' : ActorMethod<[string, string], boolean>,
  'endJourney' : ActorMethod<[string, string], boolean>,
  'getActiveJourney' : ActorMethod<[string], [] | [JourneySession]>,
  'getAlertLogs' : ActorMethod<[string], Array<AlertLog>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmergencyContacts' : ActorMethod<[string], Array<EmergencyContact>>,
  'getProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'getSafeZones' : ActorMethod<[string], Array<SafeZone>>,
  'getSystemStats' : ActorMethod<[], SystemStats>,
  'getTwilioStatus' : ActorMethod<
    [],
    {
      'isMockMode' : boolean,
      'configured' : boolean,
      'fromNumber' : [] | [string],
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveEmergencyContact' : ActorMethod<[string, EmergencyContact], string>,
  'saveProfile' : ActorMethod<[string, UserProfile], boolean>,
  'saveSafeZone' : ActorMethod<[string, SafeZone], string>,
  'sendAutoLocationAlert' : ActorMethod<
    [string, number, number, string, bigint],
    AlertResult
  >,
  'sendSosAlert' : ActorMethod<
    [string, number, number, number, string, bigint],
    AlertResult
  >,
  'setTwilioConfig' : ActorMethod<[string, string, string], boolean>,
  'startJourney' : ActorMethod<[string, string, bigint], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateJourneyLocation' : ActorMethod<[string, number, number], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];