/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface JourneySession {
    id: string;
    startTime: bigint;
    status: string;
    destination: string;
    userId: string;
    isActive: boolean;
    currentLong: number;
    currentLat: number;
    estimatedArrival: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface AlertResult {
    status: string;
    contactsNotified: bigint;
    mapLink: string;
    isMockMode: boolean;
    failedContacts: Array<string>;
    providerUsed: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface SystemStats {
    totalAutoAlerts: bigint;
    failedDeliveries: bigint;
    totalSosAlerts: bigint;
    totalUsers: bigint;
    totalDeliveries: bigint;
}
export interface SafeZone {
    id: string;
    lat: number;
    long: number;
    name: string;
    zoneLabel: string;
    radius: number;
}
export interface EmergencyContact {
    id: string;
    relationship: string;
    isGuardian: boolean;
    name: string;
    phone: string;
}
export interface AlertLog {
    id: string;
    lat: number;
    alertType: string;
    contactsNotified: bigint;
    mapLink: string;
    isMockMode: boolean;
    userId: string;
    long: number;
    errorDetails?: string;
    failedContacts: Array<string>;
    timestamp: bigint;
    providerUsed: string;
    overallStatus: string;
    locationAccuracy: number;
}
export interface UserProfile {
    name: string;
    email: string;
    bloodGroup?: string;
    address?: string;
    phone: string;
}
export interface http_header {
    value: string;
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearAlertLogs(userId: string): Promise<boolean>;
    deleteEmergencyContact(userId: string, contactId: string): Promise<boolean>;
    deleteSafeZone(userId: string, zoneId: string): Promise<boolean>;
    endJourney(journeyId: string, status: string): Promise<boolean>;
    getActiveJourney(userId: string): Promise<JourneySession | null>;
    getAlertLogs(userId: string): Promise<Array<AlertLog>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEmergencyContacts(userId: string): Promise<Array<EmergencyContact>>;
    getProfile(userId: string): Promise<UserProfile | null>;
    getSafeZones(userId: string): Promise<Array<SafeZone>>;
    getSystemStats(): Promise<SystemStats>;
    getTwilioStatus(): Promise<{
        isMockMode: boolean;
        configured: boolean;
        fromNumber?: string;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveEmergencyContact(userId: string, contact: EmergencyContact): Promise<string>;
    saveProfile(userId: string, profile: UserProfile): Promise<boolean>;
    saveSafeZone(userId: string, zone: SafeZone): Promise<string>;
    sendAutoLocationAlert(userId: string, lat: number, long: number, userName: string, timestamp: bigint): Promise<AlertResult>;
    sendSosAlert(userId: string, lat: number, long: number, accuracy: number, userName: string, timestamp: bigint): Promise<AlertResult>;
    setTwilioConfig(sid: string, authToken: string, fromNumber: string): Promise<boolean>;
    startJourney(userId: string, destination: string, estimatedArrival: bigint): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateJourneyLocation(journeyId: string, lat: number, long: number): Promise<boolean>;
}
import type { AlertLog as _AlertLog, JourneySession as _JourneySession, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearAlertLogs(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAlertLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAlertLogs(arg0);
            return result;
        }
    }
    async deleteEmergencyContact(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmergencyContact(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmergencyContact(arg0, arg1);
            return result;
        }
    }
    async deleteSafeZone(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSafeZone(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSafeZone(arg0, arg1);
            return result;
        }
    }
    async endJourney(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.endJourney(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endJourney(arg0, arg1);
            return result;
        }
    }
    async getActiveJourney(arg0: string): Promise<JourneySession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveJourney(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveJourney(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlertLogs(arg0: string): Promise<Array<AlertLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertLogs(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertLogs(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmergencyContacts(arg0: string): Promise<Array<EmergencyContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmergencyContacts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmergencyContacts(arg0);
            return result;
        }
    }
    async getProfile(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSafeZones(arg0: string): Promise<Array<SafeZone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSafeZones(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSafeZones(arg0);
            return result;
        }
    }
    async getSystemStats(): Promise<SystemStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemStats();
            return result;
        }
    }
    async getTwilioStatus(): Promise<{
        isMockMode: boolean;
        configured: boolean;
        fromNumber?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTwilioStatus();
                return from_candid_record_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTwilioStatus();
            return from_candid_record_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveEmergencyContact(arg0: string, arg1: EmergencyContact): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEmergencyContact(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEmergencyContact(arg0, arg1);
            return result;
        }
    }
    async saveProfile(arg0: string, arg1: UserProfile): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(arg0, to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(arg0, to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveSafeZone(arg0: string, arg1: SafeZone): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSafeZone(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSafeZone(arg0, arg1);
            return result;
        }
    }
    async sendAutoLocationAlert(arg0: string, arg1: number, arg2: number, arg3: string, arg4: bigint): Promise<AlertResult> {
        if (this.processError) {
            try {
                const result = await this.actor.sendAutoLocationAlert(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendAutoLocationAlert(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async sendSosAlert(arg0: string, arg1: number, arg2: number, arg3: number, arg4: string, arg5: bigint): Promise<AlertResult> {
        if (this.processError) {
            try {
                const result = await this.actor.sendSosAlert(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendSosAlert(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async setTwilioConfig(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setTwilioConfig(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTwilioConfig(arg0, arg1, arg2);
            return result;
        }
    }
    async startJourney(arg0: string, arg1: string, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.startJourney(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startJourney(arg0, arg1, arg2);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateJourneyLocation(arg0: string, arg1: number, arg2: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJourneyLocation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJourneyLocation(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AlertLog_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertLog): AlertLog {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JourneySession]): JourneySession | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    bloodGroup: [] | [string];
    address: [] | [string];
    phone: string;
}): {
    name: string;
    email: string;
    bloodGroup?: string;
    address?: string;
    phone: string;
} {
    return {
        name: value.name,
        email: value.email,
        bloodGroup: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.bloodGroup)),
        address: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.address)),
        phone: value.phone
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isMockMode: boolean;
    configured: boolean;
    fromNumber: [] | [string];
}): {
    isMockMode: boolean;
    configured: boolean;
    fromNumber?: string;
} {
    return {
        isMockMode: value.isMockMode,
        configured: value.configured,
        fromNumber: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.fromNumber))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    lat: number;
    alertType: string;
    contactsNotified: bigint;
    mapLink: string;
    isMockMode: boolean;
    userId: string;
    long: number;
    errorDetails: [] | [string];
    failedContacts: Array<string>;
    timestamp: bigint;
    providerUsed: string;
    overallStatus: string;
    locationAccuracy: number;
}): {
    id: string;
    lat: number;
    alertType: string;
    contactsNotified: bigint;
    mapLink: string;
    isMockMode: boolean;
    userId: string;
    long: number;
    errorDetails?: string;
    failedContacts: Array<string>;
    timestamp: bigint;
    providerUsed: string;
    overallStatus: string;
    locationAccuracy: number;
} {
    return {
        id: value.id,
        lat: value.lat,
        alertType: value.alertType,
        contactsNotified: value.contactsNotified,
        mapLink: value.mapLink,
        isMockMode: value.isMockMode,
        userId: value.userId,
        long: value.long,
        errorDetails: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.errorDetails)),
        failedContacts: value.failedContacts,
        timestamp: value.timestamp,
        providerUsed: value.providerUsed,
        overallStatus: value.overallStatus,
        locationAccuracy: value.locationAccuracy
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AlertLog>): Array<AlertLog> {
    return value.map((x)=>from_candid_AlertLog_n5(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    bloodGroup?: string;
    address?: string;
    phone: string;
}): {
    name: string;
    email: string;
    bloodGroup: [] | [string];
    address: [] | [string];
    phone: string;
} {
    return {
        name: value.name,
        email: value.email,
        bloodGroup: value.bloodGroup ? candid_some(value.bloodGroup) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        phone: value.phone
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
